<?php

namespace Tests\Unit\Departments;

use App\Models\User;
use App\Services\Department\DepartmentService;
use Database\Factories\DepartmentFactory;
use Database\Factories\UserFactory;
use Database\Seeders\DepartmentsSeeder;
use Database\Seeders\UserSeeder;
use Tests\TestCase;

class DepartmentServiceTests extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(UserSeeder::class);
        $this->seed(DepartmentsSeeder::class);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function set_users_to_department()
    {
        $userFactory = new UserFactory();
        $deptFactory = new DepartmentFactory();

        $user1 = $userFactory->create();
        $user2 = $userFactory->create();
        $user3 = $userFactory->create();

        $dept = $deptFactory->create();
        $dept->belongsToMany(User::class,'department_user');
        $dept->belongsToMany(User::class)->attach([$user1->id, $user2->id]);

        $departmentService = new DepartmentService();
        $departmentService->setUsersToDepartment($dept, collect([$user3]));

        $this->assertEquals($user3->id, $dept->users->first()->id);
        $this->assertCount(1, $dept->users);

    }
}
