<?php

namespace Tests;

use App\Repositories\DepartmentRepository;
use App\Repositories\UserRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use RefreshDatabase;
    protected DepartmentRepository $departmentRepository;
    protected UserRepository $userRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->departmentRepository = new DepartmentRepository();
        $this->userRepository = new UserRepository();
    }
}
